name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "24649544-f9610eb5-234f-4bcd-bfc4-d81eead3068c" -e "24649544-1d9ea059-2e26-46c0-bab6-2f90a49b5171"
      - name: Logout from Postman CLI
        run: postman logout ${{ secrets.POSTMAN_API_KEY }}
